about: 'Phần mềm được thiết kế từ TuanPham ( fb.me/rayz9x ) và host của heroku'
About: 'Phần mềm được thiết kế từ TuanPham ( fb.me/rayz9x ) và host của heroku'
hi: 'Nice to miss u'
Hi: 'Hola'
hello: 'Hello world! :v'
Hello: 'Hello world! ;)'
help: 'U can find chat as hello,hi,help,time,clock,...'
HELP: 'U can find chat as hello,hi,help,time,clock,...'
Help: 'U can find chat as hello,hi,help,time,clock,...'
time: 'time is thời gian'
clock: ' clock is đồng hồ'
error: 'I have not been taught this word'
