about: 'Phần mềm được thiết kế từ TuanPham ( fb.me/rayz9x ) và host của heroku'
hi: 'Nice to miss u'
hello: 'Hello world! :v'
help: 'U can find chat as IP, about, iLLC,LLC,...'
time: 'time is thời gian'
clock: ' clock is đồng hồ'
error: 'I have not been taught this word'
